# Generated by Django 5.2.3 on 2025-11-01 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TOMATO", "Tomato"),
                            ("POTATO", "Potato"),
                            ("PEPPER", "Pepper (Bell)"),
                            ("WHEAT", "Wheat"),
                            ("RICE", "Rice"),
                            ("CORN", "Corn"),
                            ("COTTON", "Cotton"),
                            ("SOYBEAN", "Soybean"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "optimal_temp_min",
                    models.FloatField(
                        help_text="Minimum optimal temperature in Celsius"
                    ),
                ),
                (
                    "optimal_temp_max",
                    models.FloatField(
                        help_text="Maximum optimal temperature in Celsius"
                    ),
                ),
                (
                    "optimal_humidity_min",
                    models.FloatField(help_text="Minimum optimal humidity percentage"),
                ),
                (
                    "optimal_humidity_max",
                    models.FloatField(help_text="Maximum optimal humidity percentage"),
                ),
                (
                    "water_requirement",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("frost_tolerance", models.BooleanField(default=False)),
                (
                    "growing_season_days",
                    models.IntegerField(help_text="Average days to harvest"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location_name", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="weather.crop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmingInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("WATERING", "Watering Recommendation"),
                            ("PLANTING", "Planting Recommendation"),
                            ("HARVESTING", "Harvesting Recommendation"),
                            ("WARNING", "Weather Warning"),
                            ("GENERAL", "General Advice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(default=1, help_text="1=Low, 2=Medium, 3=High"),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="weather.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                (
                    "feels_like",
                    models.FloatField(help_text="Feels like temperature in Celsius"),
                ),
                ("humidity", models.FloatField(help_text="Humidity percentage")),
                (
                    "pressure",
                    models.FloatField(help_text="Atmospheric pressure in hPa"),
                ),
                ("wind_speed", models.FloatField(help_text="Wind speed in m/s")),
                (
                    "precipitation",
                    models.FloatField(default=0, help_text="Precipitation in mm"),
                ),
                ("weather_condition", models.CharField(max_length=100)),
                ("weather_description", models.CharField(max_length=200)),
                ("clouds", models.FloatField(help_text="Cloudiness percentage")),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="weather.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
